try:
    x = 5
    print(x)
except:
    print("An exception occurred.")
else:
    print("No exception occurred.")


